import os
base = r'алgorithms'
with open(os.path.join(base, 'dea.py'), 'w', encoding='utf-8') as f:
    f.write('# DEA Data Envelopment Analysis\n')
    f.write('import numpy as np\n')
    f.write('from scipy.optimize import linprog\n\n')
    f.write('class DEA:\n')
    f.write('    def __init__(self):\n')
    f.write('        self.results = None\n\n')
    f.write('    def evaluate(self, X, Y, target_idx=None):\n')
    f.write('        m, n = X.shape\n')
    f.write('        if target_idx is None:\n')
    f.write('            target_idx = list(range(n))\n')
    f.write('        efficiencies = {}\n')
    f.write('        for idx in target_idx:\n')
    f.write('            c = np.zeros(m + 1)\n')
    f.write('            A_ub = -X.T\n')
    f.write('            b_ub = np.zeros(n)\n')
    f.write('            A_eq = np.zeros((1, m))\n')
    f.write('            A_eq[0] = X[:, idx]\n')
    f.write('            b_eq = np.array([1.0])\n')
    f.write('            bounds = [(0, None)] * m\n')
    f.write('            result = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method="highs")\n')
    f.write('            if result.success:\n')
    f.write('                efficiencies[idx] = float(result.fun)\n')
    f.write('            else:\n')
    f.write('                efficiencies[idx] = None\n')
    f.write('        self.results = efficiencies\n')
    f.write('        return efficiencies\n\n')
    f.write('    def classify_efficiency(self, efficiencies, threshold=0.8):\n')
    f.write('        classification = {}\n')
    f.write('        for idx, eff in efficiencies.items():\n')
    f.write('            if eff is None:\n')
    f.write('                classification[idx] = "failed"\n')
    f.write('            elif eff >= 1.0:\n')
    f.write('                classification[idx] = "effective"\n')
    f.write('            elif eff >= threshold:\n')
    f.write('                classification[idx] = "near_effective"\n')
    f.write('            else:\n')
    f.write('                classification[idx] = "ineffective"\n')
    f.write('        return classification\n')
print('Created dea.py')
